### ISSUE TITLE
Cannot import AHRS

### ISSUE THREAD

**Issue by benjiboy50fonz** [robotpy/robotpy-navx#12]
On Arch Linux, with packages from tortall.net and building robotpy-navx locally, I see the following error:
```
Python 3.8.1 (default, Jan 22 2020, 06:38:00) 
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from navx import AHRS
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/coder/code/pybot/.venv/lib/python3.8/site-packages/navx/__init__.py", line 4, in <module>
    from ._navx import AHRS
ImportError: generic_type: type "AHRS" referenced unknown base type "frc::SendableBase"
```

**Comment by virtuald** [comment]
Most likely it's using a wheel built with an older version of robotpy-build. Try building with `--no-cache-dir` specified?

I'll try to upload a wheel to tortall tonight, there currently aren't any wheels there.

**Comment by benjiboy50fonz** [comment]
It was built with the ``` --no-cache-dir``` flag specified.

**Comment by auscompgeek** [comment]
Huh, I never realised there wasn't any robotpy-navx wheels on tortall. I've built one on Ubuntu bionic here: https://devpi.vovo.id.au/davo/robotpy-bionic/robotpy-navx/2020.1.0

**Comment by virtuald** [comment]
Awesome. Also, I just pushed 2020.2.0, which has the magic to upload linux wheels to tortall, so you shouldn't have this issue in the future. Sorry about that!

**Comment by benjiboy50fonz** [comment]
Thanks!
